"""The cTrader Open API v2 protobuf messages, generated by Spotware.

Vendored unchanged from ``ctrader-open-api`` 0.9.2 (MIT, Copyright (c) 2021
Spotware — ``LICENSE.spotware``) except for their package imports. Only the
messages are taken: the SDK's Twisted client queues every send for up to a
second and hard-pins pyOpenSSL, so the gateway speaks the wire itself
(:mod:`atjte.gateways.ctrader.transport`) and needs only ``protobuf``.
"""
